// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TSGTS.DataAccess;

#nullable disable

namespace TSGTS.DataAccess.Migrations
{
    [DbContext(typeof(TsgtsDbContext))]
    partial class TsgtsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TSGTS.Core.Entities.ActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("IslemAciklamasi");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("KayitId");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("ZamanDamgasi");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("KullaniciId");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("IslemLoglari", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("AtamaTarihi");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int")
                        .HasColumnName("TeknisyenId");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("KayitId");

                    b.HasKey("Id");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("TicketId");

                    b.ToTable("Atamalar", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)")
                        .HasColumnName("MarkaAdi");

                    b.HasKey("Id");

                    b.ToTable("Markalar", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)")
                        .HasColumnName("KategoriAdi");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Eposta");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)")
                        .HasColumnName("Ad");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)")
                        .HasColumnName("Soyad");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefon");

                    b.Property<string>("TaxNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("VergiNo");

                    b.HasKey("Id");

                    b.HasIndex("TaxNo")
                        .IsUnique()
                        .HasFilter("[TaxNo] IS NOT NULL");

                    b.ToTable("Musteriler", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("MarkaId");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("ModelId");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SatinAlmaTarihi");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SeriNo");

                    b.Property<DateTime?>("WarrantyEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("GarantiBitisTarihi");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ModelId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Cihazlar", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Indirim");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NetTutar");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FaturaTarihi");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("KDV");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("KayitId");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ToplamTutar");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Faturalar", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.LaborRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SaatlikUcret");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HizmetTuru");

                    b.HasKey("Id");

                    b.ToTable("IscilikUcretleri", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("MarkaId");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("KategoriId");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModelAdi");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Modeller", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Tutar");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Tarih");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("FaturaId");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("OdemeTipiId");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Odemeler", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TipAdi");

                    b.HasKey("Id");

                    b.ToTable("OdemeTipleri", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RolAdi");

                    b.HasKey("Id");

                    b.ToTable("Roller", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.ServicePartUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("ParcaId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Miktar");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("KayitId");

                    b.Property<DateTime>("UsedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("KullanimTarihi");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("TicketId");

                    b.ToTable("ServisParcaKullanimlari", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.ServiceTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("MusteriId");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Aciklama");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("CihazId");

                    b.Property<int>("OpenedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("AcanKullaniciId");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("DurumId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("OpenedByUserId");

                    b.HasIndex("StatusId");

                    b.ToTable("ServisKayitlari", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.SparePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriticalLevel")
                        .HasColumnType("int")
                        .HasColumnName("KritikSeviye");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ParcaKodu");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ParcaAdi");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("StokMiktari");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BirimFiyat");

                    b.HasKey("Id");

                    b.HasIndex("PartCode")
                        .IsUnique();

                    b.ToTable("YedekParcalar", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.TicketStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("RenkKodu");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DurumAdi");

                    b.HasKey("Id");

                    b.ToTable("ServisDurumlari", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Eposta");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Aktif");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("SifreOzeti");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KullaniciAdi");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("TSGTS.Core.Entities.ActionLog", b =>
                {
                    b.HasOne("TSGTS.Core.Entities.ServiceTicket", "Ticket")
                        .WithMany("ActionLogs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TSGTS.Core.Entities.User", "User")
                        .WithMany("ActionLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Assignment", b =>
                {
                    b.HasOne("TSGTS.Core.Entities.User", "Technician")
                        .WithMany("Assignments")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TSGTS.Core.Entities.ServiceTicket", "Ticket")
                        .WithMany("Assignments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technician");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Device", b =>
                {
                    b.HasOne("TSGTS.Core.Entities.Brand", "Brand")
                        .WithMany("Devices")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TSGTS.Core.Entities.Model", "Model")
                        .WithMany("Devices")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Invoice", b =>
                {
                    b.HasOne("TSGTS.Core.Entities.ServiceTicket", "Ticket")
                        .WithMany("Invoices")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Model", b =>
                {
                    b.HasOne("TSGTS.Core.Entities.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TSGTS.Core.Entities.Category", "Category")
                        .WithMany("Models")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Payment", b =>
                {
                    b.HasOne("TSGTS.Core.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TSGTS.Core.Entities.PaymentType", "PaymentType")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.ServicePartUsage", b =>
                {
                    b.HasOne("TSGTS.Core.Entities.SparePart", "Part")
                        .WithMany("PartUsages")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TSGTS.Core.Entities.ServiceTicket", "Ticket")
                        .WithMany("PartUsages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.ServiceTicket", b =>
                {
                    b.HasOne("TSGTS.Core.Entities.Customer", "Customer")
                        .WithMany("ServiceTickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TSGTS.Core.Entities.Device", "Device")
                        .WithMany("ServiceTickets")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TSGTS.Core.Entities.User", "OpenedByUser")
                        .WithMany("OpenedTickets")
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TSGTS.Core.Entities.TicketStatus", "Status")
                        .WithMany("ServiceTickets")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Device");

                    b.Navigation("OpenedByUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.User", b =>
                {
                    b.HasOne("TSGTS.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Brand", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Category", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Customer", b =>
                {
                    b.Navigation("ServiceTickets");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Device", b =>
                {
                    b.Navigation("ServiceTickets");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Model", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.PaymentType", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.ServiceTicket", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("Assignments");

                    b.Navigation("Invoices");

                    b.Navigation("PartUsages");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.SparePart", b =>
                {
                    b.Navigation("PartUsages");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.TicketStatus", b =>
                {
                    b.Navigation("ServiceTickets");
                });

            modelBuilder.Entity("TSGTS.Core.Entities.User", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("Assignments");

                    b.Navigation("OpenedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
